# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170222_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='lobby.Lobby'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lobby_owned',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='lobby.Lobby'),
        ),
    ]
