# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20170220_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lobby',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
