# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lobby', '0003_remove_lobby_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
