# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0008_auto_20170220_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
