# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0011_auto_20170221_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lobby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='lobby.Lobby'),
        ),
    ]
