# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0014_auto_20170221_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='is_full',
            field=models.BooleanField(),
        ),
    ]
