# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0015_auto_20170221_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='asd',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
