# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0016_profile_asd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='asd',
        ),
    ]
